version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8284:8284"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:Zxcvbnm123@postgres:5432/kube

  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Zxcvbnm123
      POSTGRES_DB: kube
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend  
