name: Deploy to k3s via CI/CD
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & push backend
      run: |
        docker build -t almuko/backend:latest ./backend
        docker push almuko/backend:latest

    - name: Build & push frontend
      run: |
        docker build -t almuko/frontend:latest ./frontend
        docker push almuko/frontend:latest

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: latest

    - name: Deploy to k3s
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        echo "$KUBECONFIG" > kubeconfig.yaml
        kubectl --kubeconfig=kubeconfig.yaml apply -f k8s/
